name: journal_trend_analyzer
description: "A Flutter app to search and analyze research publication trends from OpenAlex API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.0

  # State management
  provider: ^6.1.2

  # Charts
  fl_chart: ^0.68.0

  # Open DOI links in browser
  url_launcher: ^6.3.0

  # Loading skeleton
  shimmer: ^3.0.0

  # Number formatting
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_analytics: ^12.4.3
  firebase_auth: ^6.5.3
  google_sign_in: ^6.2.1
  firebase_storage: ^13.4.3
  firebase_messaging: ^16.4.0
  firebase_crashlytics: ^5.2.4
  firebase_remote_config: ^6.5.3
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  patrol: ^4.6.1
  patrol_finders: ^3.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
