// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EKfHcoXVKbwWpuEXDGqQx-P4hvMNv8k',
    appId: '1:506419531582:web:07221a8d81c6b3b26ea66f',
    messagingSenderId: '506419531582',
    projectId: 'prm393-lab3-analyzer',
    authDomain: 'prm393-lab3-analyzer.firebaseapp.com',
    storageBucket: 'prm393-lab3-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXoMFBvkU_1uzPCCrAbyXp73KrvW78wlg',
    appId: '1:506419531582:android:dd3d8f4fde15d71e6ea66f',
    messagingSenderId: '506419531582',
    projectId: 'prm393-lab3-analyzer',
    storageBucket: 'prm393-lab3-analyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZdT7ItWknZIjb8Ebz2IqpaJ58AcOaQc',
    appId: '1:506419531582:ios:e434bba4c5ccfd236ea66f',
    messagingSenderId: '506419531582',
    projectId: 'prm393-lab3-analyzer',
    storageBucket: 'prm393-lab3-analyzer.firebasestorage.app',
    iosBundleId: 'com.prm393.journalTrendAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZdT7ItWknZIjb8Ebz2IqpaJ58AcOaQc',
    appId: '1:506419531582:ios:e434bba4c5ccfd236ea66f',
    messagingSenderId: '506419531582',
    projectId: 'prm393-lab3-analyzer',
    storageBucket: 'prm393-lab3-analyzer.firebasestorage.app',
    iosBundleId: 'com.prm393.journalTrendAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_EKfHcoXVKbwWpuEXDGqQx-P4hvMNv8k',
    appId: '1:506419531582:web:2ccd09887c9902126ea66f',
    messagingSenderId: '506419531582',
    projectId: 'prm393-lab3-analyzer',
    authDomain: 'prm393-lab3-analyzer.firebaseapp.com',
    storageBucket: 'prm393-lab3-analyzer.firebasestorage.app',
  );
}
